title: Christopher Penkin
email: chris@penkin.me
description: >- # this means to ignore newlines until "baseurl:"
  Christopher shares projects, lessons, and thoughts on clean code, UX design, and creative tinkering—both digital and analog.
baseurl: ""
url: "https://www.penkin.me"
google_analytics: G-52NN17J06E
locale: en_ZA

jekyll_version: "3.10.0"
highlighter: rouge

paginate: 10
paginate_path: "/blog/page:num/"

twitter:
  username: penkin
  card: summary

social:
  name: Christopher Penkin
  links:
    - https://twitter.com/penkin
    - https://bsky.app/profile/chrispenkin.bsky.social
    - https://www.linkedin.com/in/penkin
    - https://github.com/penkin

navigation:
  - title: About
    url: /
  - title: Blog
    url: /blog
  - title: RSS Feed
    url: /feed.xml

plugins:
  - jekyll-feed
  - jekyll-paginate
