title: Don't Jump
email: chris@penkin.me
description: >- # this means to ignore newlines until "baseurl:"
  Don't Jump is a look inside some of my thoughts and ideas. I write here from time
  to time about anything that catches my fancy.
baseurl: ""
url: "https://penkin.me"
google_analytics: G-52NN17J06E

highlighter: rouge

paginate: 5
paginate_path: "/blog/page:num/"

# kramdown:
#   parse_block_html: true

social:
  - title: Twitter
    url: https://twitter.com/penkin
  - title: GitHub
    url: https://github.com/penkin

navigation:
  - title: About
    url: /
  - title: Blog
    url: /blog

plugins:
  - jekyll-feed
  - jekyll-paginate
