title: Don't Jump
description: Christian. Husband. Father. South African. Nerd.
url: ""
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
header: large

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about

social:
  github: penkin
  twitter: penkin
  facebook: 
  email: 
  linkedin: penkin

clicky_analytics: 101164136

disqus:
    shortname: 
